name: Deploy to MuleSoft Runtime Fabric

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

  build-application:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build with Maven
        run: mvn clean package

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mule-application
          path: target/tebogohello-mule-application-v1.jar

  generate-oauth-token:
    runs-on: ubuntu-latest
    needs: build-application
    steps:
      - name: Generate OAuth Token
        id: generate_token
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          curl_response=$(curl -s --location --request POST "https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token" \
            --header "Content-Type: application/json" \
            --data-raw "{
              \"grant_type\": \"client_credentials\",
              \"client_id\": \"${CLIENT_ID}\",
              \"client_secret\": \"${CLIENT_SECRET}\"
            }")
          echo "access_token=$(echo $curl_response | jq -r '.access_token')" >> $GITHUB_ENV

  deploy-application:
    runs-on: ubuntu-latest
    needs: generate-oauth-token
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: mule-application

      - name: Deploy to MuleSoft Runtime Fabric
        env:
          ACCESS_TOKEN: ${{ env.access_token }}
        run: |
          curl --location --request POST "https://anypoint.mulesoft.com/runtimefabric/api/v1/applications" \
          --header "Authorization: Bearer $ACCESS_TOKEN" \
          --header "Content-Type: application/json" \
          --data-raw "{
              \"name\": \"my-app-dev\",
              \"file\": \"path/to/your/tebogohello-mule-application-v1.jar\",
              \"runtimeVersion\": \"4.3.0\",
              \"replicas\": 2,
              \"properties\": {
                \"anypoint.platform.client_id\": \"${CLIENT_ID}\",
                \"anypoint.platform.client_secret\": \"${CLIENT_SECRET}\"
              }
          }"
