name: Publish to MuleSoft Exchange via Client App

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build the MuleSoft Application
        run: mvn clean package

      - name: Install Client App
        run: |
          # Replace the following with the actual installation command for your client app
          curl -L https://example.com/download/client-app -o client-app
          chmod +x client-app
          sudo mv client-app /usr/local/bin/

      - name: Generate OAuth Token
        id: generate-token
        run: |
          response=$(curl -s -X POST https://your-auth-server.com/oauth/token \
            -d "grant_type=client_credentials" \
            -d "client_id=${{ secrets.CLIENT_APP_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.CLIENT_APP_CLIENT_SECRET }}")
          echo "access_token=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV

      - name: Publish to MuleSoft Exchange via Client App
        env:
          ACCESS_TOKEN: ${{ env.access_token }}
        run: |
          client-app publish --file target/your-application-name-1.0.0-mule-application.zip --access-token $ACCESS_TOKEN
