name: Publish to MuleSoft Exchange

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build the MuleSoft Application
        run: mvn clean package

      - name: Install MuleSoft CLI
        run: |
          curl -L https://anypoint.mulesoft.com/downloads/mule/mule-4.3.0.zip --output mule.zip
          unzip mule.zip -d /usr/local/
          export PATH=$PATH:/usr/local/mule-4.3.0/bin

      - name: Authenticate with MuleSoft Anypoint Platform
        env:
          MULE_USERNAME: ${{ secrets.MULE_USERNAME }}
          MULE_PASSWORD: ${{ secrets.MULE_PASSWORD }}
        run: mule login -u $MULE_USERNAME -p $MULE_PASSWORD

      - name: Publish to MuleSoft Exchange
        env:
          MULE_ORG_ID: ${{ secrets.MULE_ORG_ID }}
        run: mule exchange:publish -f target/your-application-name-1.0.0-mule-application.zip --organizationId $MULE_ORG_ID
